spring:
  cloud:
    gateway:
      discovery:
        locator: #Enables the gateway to create routes based on services registered with service discovery
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: organization-service
        uri: lb://ORGANIZATION-SERVICE
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}

      - id: licensing-service
        uri: lb://LICENSING-SERVICE
        predicates:
        - Path=/license/**
        filters:
        - RewritePath=/license/(?<path>.*), /$\{path}

      - id: licensing-service-dynamic
        uri: lb://LICENSING-SERVICE
        predicates:
        - Path=/license-dynamic/**
        filters:
        - RewritePath=/license-dynamic/(?<path>.*), /$\{path}

      - id: google
        uri: https://www.google.com
        predicates:
        - Path=/google/**
        filters:
        - RewritePath=/google(?<path>.*), /

      - id: baylor
        uri: https://www.baylor.edu
        predicates:
        - Path=/baylor/**
        filters:
        - RewritePath=/baylor(?<path>.*), /

logging:
  level:
    root: DEBUG

server:
  port: 8091
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server1:8070/eureka/,http://eureka-server2:8071/eureka/,http://eureka-server3:8072/eureka/

management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true
    health.enabled: true
  endpoint:
    health.enabled: true
    health.show-details: always
    metrics.enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
