spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      show-sql: true
      format-sql: true
    defer-datasource-initialization: true
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8070/eureka/, http://eureka-server:8071/eureka/, http://eureka-server:8072/eureka/

sql:
  init:
    mode: always

management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true
    health.enabled: true
    health.show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true