spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      show-sql: true
      format-sql: true
    defer-datasource-initialization: true
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8070/eureka/,http://eureka-server2:8071/eureka/,http://eureka-server3:8072/eureka/

sql:
  init:
    mode: always

management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true
    health.enabled: true
  endpoint:
    health.enabled: true
    health.show-details: always
    metrics.enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 3s
      failureRateThreshold: 20
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
#      ignoreExceptions:
  instances:
    organizationService:
      baseConfig: default
    licenseService:
      baseConfig: default